version: '3.9'

services:
  ansible:
    container_name: ansible
    image: ansible
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile

  remote-host-one:
    container_name: remote-host-one
    image: remote-host-ssh
    build:
      context: ./ssh-enabled-ubuntu
      dockerfile: Dockerfile

networks:
  net:

# docker-compose up -d